In [65]:
import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [95]:
def evaluation_metrics(file_path):
    df = pd.read_csv(file_path, parse_dates=['timestamp'])

    # Calculate log return
    df['log_return'] = np.log(df['total_value'] / df['total_value'].shift(1))

    # === Metrics ===
    # 1. Total Return (Simple)
    total_return = df["total_value"].iloc[-1] / df["total_value"].iloc[0] - 1
    
    # 2. Mean Log Return (Hourly)
    mean_log_return = df["log_return"].mean()
    
    # 3. Standard Deviation of Log Return
    std_log_return = df["log_return"].std()
    
    # 4. Sharpe Ratio: Risk-adjusted return (assuming 0 risk-free rate)
    sharpe_ratio = mean_log_return / std_log_return if std_log_return != 0 else np.nan
    
    # 5. Max Drawdown
    # (1) Compute the running maximum of the total value (the highest value up to each time point)
    cumulative_max = df["total_value"].cummax()
    # (2) Calculate the drawdown as the percentage drop from the running max: Drawdown = 1 - current_value / peak_value
    drawdowns = 1 - df["total_value"] / cumulative_max
    # (3) Max drawdown is the worst drop observed
    max_drawdown = drawdowns.max()

    print(f"=== EVALUATION METRICS ===")
    print(f"Total Return: {total_return:.4f}")
    print(f"Hourly Mean Log Return: {mean_log_return:.4f}")
    print(f"Hourly Std of Log Return: {std_log_return:.4f}")
    print(f"Hourly Sharpe Ratio: {sharpe_ratio:.4f}")
    print(f"Max Drawdown: {max_drawdown:.4f}")

    metrics = {
        'Total Return': total_return,
        'Hourly Mean Log Return': mean_log_return,
        'Hourly Std of Log Return': std_log_return,
        'Sharpe Ratio': sharpe_ratio,
        'Max Drawdown': max_drawdown,
    }

    return metrics, df

## A. Model Results

In [96]:
# Bullish 1
file_path = "data/model/bullish/bullish_1_2024-11-05_2024-11-11_0.01_0.8.csv"
metrics_bullish_1, df_bullish_1 = evaluation_metrics(file_path)

=== EVALUATION METRICS ===
Total Return: 0.2480
Hourly Mean Log Return: 0.0013
Hourly Std of Log Return: 0.0051
Hourly Sharpe Ratio: 0.2579
Max Drawdown: 0.0337

In [97]:
print(metrics_bullish_1)

{'Total Return': 0.24802928325867746, 'Hourly Mean Log Return': 0.0013267409210870609, 'Hourly Std of Log Return': 0.005143980940460938, 'Sharpe Ratio': 0.25792104139642774, 'Max Drawdown': 0.03367988452269399}

In [98]:
df_bullish_1

,timestamp,portfolio,scores,total_value,log_return
0,2024-11-05 00:00:00,"{'BTC': 0.04082049518265892, 'ETH': 0.69395082...","{'BTC': 0.5, 'ETH': 0.3, 'SOL': 0.6, 'DOGE': 0...",9.993857e+05,NaN
1,2024-11-05 01:00:00,"{'BTC': 0.09595553632287367, 'ETH': 1.21232871...","{'BTC': 0.6, 'ETH': 0.2, 'SOL': 0.5, 'DOGE': 0...",9.993347e+05,-0.000051
2,2024-11-05 02:00:00,"{'BTC': 0.13927208562761473, 'ETH': 1.70141630...","{'BTC': 0.5, 'ETH': 0.2, 'SOL': 0.6, 'DOGE': 0...",9.993853e+05,0.000051
3,2024-11-05 03:00:00,"{'BTC': 0.1925548511853592, 'ETH': 2.264824113...","{'BTC': 0.8, 'ETH': 0.3, 'SOL': 0.6, 'DOGE': 0...",9.995630e+05,0.000178
4,2024-11-05 04:00:00,"{'BTC': 0.2474319789485589, 'ETH': 2.779498053...","{'BTC': 0.6, 'ETH': 0.2, 'SOL': 0.5, 'DOGE': 0...",9.996230e+05,0.000060
...,...,...,...,...,...
163,2024-11-11 19:00:00,"{'BTC': 5.455751282622801, 'ETH': 93.441974392...","{'BTC': 0.8, 'ETH': 0.6, 'SOL': 0.5, 'DOGE': 0...",1.211315e+06,-0.003129
164,2024-11-11 20:00:00,"{'BTC': 5.455751282622801, 'ETH': 93.441974392...","{'BTC': 0.8, 'ETH': 0.6, 'SOL': 0.5, 'DOGE': 0...",1.222441e+06,0.009143
165,2024-11-11 21:00:00,"{'BTC': 5.455751282622801, 'ETH': 93.441974392...","{'BTC': 0.8, 'ETH': 0.6, 'SOL': 0.5, 'DOGE': 0...",1.227861e+06,0.004424
166,2024-11-11 22:00:00,"{'BTC': 5.455751282622801, 'ETH': 93.441974392...","{'BTC': 0.8, 'ETH': 0.6, 'SOL': 0.5, 'DOGE': 0...",1.231128e+06,0.002657
167,2024-11-11 23:00:00,"{'BTC': 5.455751282622801, 'ETH': 93.441974392...","{'BTC': 0.8, 'ETH': 0.6, 'SOL': 0.5, 'DOGE': 0...",1.247263e+06,0.013021

In [99]:
# Bullish 2
file_path = "data/model/bullish/bullish_2_2024-11-18_2024-11-24_0.01_0.6.csv"
metrics_bullish_2, df_bullish_2 = evaluation_metrics(file_path)

=== EVALUATION METRICS ===
Total Return: 0.0511
Hourly Mean Log Return: 0.0003
Hourly Std of Log Return: 0.0044
Hourly Sharpe Ratio: 0.0680
Max Drawdown: 0.0535

In [100]:
# Bullish 3
file_path = "data/model/bullish/bullish_3_2024-11-26_2024-12-02_0.1_0.6.csv"
metrics_bullish_3, df_bullish_3 = evaluation_metrics(file_path)

=== EVALUATION METRICS ===
Total Return: 0.0773
Hourly Mean Log Return: 0.0004
Hourly Std of Log Return: 0.0056
Hourly Sharpe Ratio: 0.0791
Max Drawdown: 0.0500

In [101]:
# Bearish 1
file_path = "data/model/bearish/bearish_1_2025-01-30_2025-02-05_0.005_1.0.csv"
metrics_bearish_1, df_bearish_1 = evaluation_metrics(file_path)

=== EVALUATION METRICS ===
Total Return: -0.0380
Hourly Mean Log Return: -0.0002
Hourly Std of Log Return: 0.0013
Hourly Sharpe Ratio: -0.1750
Max Drawdown: 0.0424

In [102]:
# Bearish 2
file_path = "data/model/bearish/bearish_2_2025-02-21_2025-02-27_0.005_1.0.csv"
metrics_bearish_2, df_bearish_2 = evaluation_metrics(file_path)

=== EVALUATION METRICS ===
Total Return: -0.0124
Hourly Mean Log Return: -0.0001
Hourly Std of Log Return: 0.0005
Hourly Sharpe Ratio: -0.1629
Max Drawdown: 0.0149

In [103]:
# Bearish 3
file_path = "data/model/bearish/bearish_3_2025-03-03_2025-03-09_0.005_1.0.csv"
metrics_bearish_3, df_bearish_3 = evaluation_metrics(file_path)

=== EVALUATION METRICS ===
Total Return: -0.0242
Hourly Mean Log Return: -0.0001
Hourly Std of Log Return: 0.0016
Hourly Sharpe Ratio: -0.0919
Max Drawdown: 0.0257

In [104]:
# Sideways 1
file_path = "data/model/sideways/sideways_1_2024-08-09_2024-08-15_0.008_0.8.csv"
metrics_sideways_1, df_sideways_1 = evaluation_metrics(file_path)

=== EVALUATION METRICS ===
Total Return: -0.0216
Hourly Mean Log Return: -0.0001
Hourly Std of Log Return: 0.0017
Hourly Sharpe Ratio: -0.0777
Max Drawdown: 0.0303

In [105]:
# Sideways 2
file_path = "data/model/sideways/sideways_2_2024-08-16_2024-08-22_0.05_1.0.csv"
metrics_sideways_2, df_sideways_2 = evaluation_metrics(file_path)

=== EVALUATION METRICS ===
Total Return: 0.0287
Hourly Mean Log Return: 0.0002
Hourly Std of Log Return: 0.0046
Hourly Sharpe Ratio: 0.0367
Max Drawdown: 0.0360

In [106]:
# Sideways 3
file_path = "data/model/sideways/sideways_3_2024-08-28_2024-09-03_0.005_1.0.csv"
metrics_sideways_3, df_sideways_3 = evaluation_metrics(file_path)

=== EVALUATION METRICS ===
Total Return: -0.0214
Hourly Mean Log Return: -0.0001
Hourly Std of Log Return: 0.0011
Hourly Sharpe Ratio: -0.1201
Max Drawdown: 0.0228

## B. Baseline 1: Uniform Distribution (Trade at Each Hour)

In [31]:
def simulate_uniform_trade_baseline(prices_df):
    assets = [col for col in prices_df.columns if col != 'timestamp']

    timestamps = []
    values = []
    all_holdings = []

    row_0 = prices_df.iloc[0]
    capital = 1_000_000 / row_0["usdt_price"] 

    prev_holdings = None

    for i in range(len(prices_df)):
        row = prices_df.iloc[i]
        timestamp = row["timestamp"]
        prices = row[assets].values    # numpy array

        # Calculate current total value
        if prev_holdings is not None:
            capital = np.sum(prev_holdings * prices) # Update capital since prices have changed
        
        per_asset_allocation = capital / 5
        holdings = per_asset_allocation / prices
        current_total_value = np.sum(holdings * prices)

        # Record
        timestamps.append(timestamp)
        values.append(current_total_value)
        all_holdings.append(holdings)

        # For next hour
        prev_holdings = holdings

    holdings_df = pd.DataFrame(all_holdings, columns=[a.replace('_price', '_holding') for a in assets])
    results_df = pd.DataFrame({'timestamp': timestamps, 'portfolio_total_value': values})
    merged_df = pd.concat([results_df, holdings_df], axis=1)
    final_df = pd.merge(merged_df, prices_df, on='timestamp')

    return final_df

In [87]:
def evaluation_metrics_for_baseline(df):

    # Calculate log return
    df['log_return'] = np.log(df['portfolio_total_value'] / df['portfolio_total_value'].shift(1))

    # === Metrics ===
    # 1. Total Return (Simple)
    total_return = df["portfolio_total_value"].iloc[-1] / df["portfolio_total_value"].iloc[0] - 1
    
    # 2. Mean Log Return (Hourly)
    mean_log_return = df["log_return"].mean()
    
    # 3. Standard Deviation of Log Return
    std_log_return = df["log_return"].std()
    
    # 4. Sharpe Ratio: Risk-adjusted return (assuming 0 risk-free rate)
    sharpe_ratio = mean_log_return / std_log_return if std_log_return != 0 else np.nan
    
    # 5. Max Drawdown
    # (1) Compute the running maximum of the total value (the highest value up to each time point)
    cumulative_max = df["portfolio_total_value"].cummax()
    # (2) Calculate the drawdown as the percentage drop from the running max: Drawdown = 1 - current_value / peak_value
    drawdowns = 1 - df["portfolio_total_value"] / cumulative_max
    # (3) Max drawdown is the worst drop observed
    max_drawdown = drawdowns.max()

    print(f"=== EVALUATION METRICS ===")
    print(f"Total Return: {total_return:.4f}")
    print(f"Hourly Mean Log Return: {mean_log_return:.4f}")
    print(f"Hourly Std of Log Return: {std_log_return:.4f}")
    print(f"Hourly Sharpe Ratio: {sharpe_ratio:.4f}")
    print(f"Max Drawdown: {max_drawdown:.4f}")

    metrics = {
        'Total Return': total_return,
        'Hourly Mean Log Return': mean_log_return,
        'Hourly Std of Log Return': std_log_return,
        'Sharpe Ratio': sharpe_ratio,
        'Max Drawdown': max_drawdown,
    }

    return metrics, df

### Bullish 1

In [88]:
prices_bullish_1 = pd.read_csv("data/prices/bullish/prices_bullish_1.csv", parse_dates=['timestamp'])

uniform_trade_bullish_1 = simulate_uniform_trade_baseline(prices_bullish_1)
uniform_trade_bullish_1.to_csv("data/baseline_1_uniform_trade/uniform_trade_bullish_1.csv", index=False)
uniform_trade_bullish_1

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2024-11-05 00:00:00,1.000615e+06,2.942690,83.376510,1262.000196,1.214667e+06,200245.961672,68006.8008,2400.2317,158.5760,0.164755,0.999386
1,2024-11-05 01:00:00,9.982446e+05,2.937328,82.849991,1261.910747,1.227687e+06,199775.620146,67969.5688,2409.7639,158.2116,0.162622,0.999366
2,2024-11-05 02:00:00,9.965909e+05,2.937289,82.912408,1259.773271,1.231016e+06,199427.188022,67857.8633,2403.9608,158.2175,0.161914,0.999453
3,2024-11-05 03:00:00,1.001395e+06,2.935924,82.784605,1254.668848,1.232581e+06,200390.598989,68216.7021,2419.2786,159.6270,0.162487,0.999443
4,2024-11-05 04:00:00,1.002484e+06,2.935157,82.583528,1253.319013,1.235914e+06,200606.583557,68308.7174,2427.8065,159.9727,0.162226,0.999453
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-11-11 19:00:00,1.367816e+06,3.171792,82.738242,1254.295719,8.603971e+05,273046.113057,86248.7761,3306.3689,218.1010,0.317950,1.001894
164,2024-11-11 20:00:00,1.378431e+06,3.168650,82.146448,1259.054802,8.573448e+05,275241.461936,87004.3072,3356.0327,218.9628,0.321558,1.001616
165,2024-11-11 21:00:00,1.387083e+06,3.152948,83.378212,1266.272547,8.387354e+05,277096.397704,87986.4262,3327.2078,219.0813,0.330756,1.001156
166,2024-11-11 22:00:00,1.387898e+06,3.152401,82.988876,1259.339305,8.469384e+05,277286.365439,88053.3825,3344.7801,220.4168,0.327745,1.001057
167,2024-11-11 23:00:00,1.415126e+06,3.189773,83.856347,1273.192276,8.049877e+05,282706.408002,88728.9508,3375.1192,222.2957,0.351589,1.001128

In [107]:
metrics_uniform_trade_bullish_1, final_uniform_trade_bullish_1 = evaluation_metrics_for_baseline(uniform_trade_bullish_1)

=== EVALUATION METRICS ===
Total Return: 0.4143
Hourly Mean Log Return: 0.0021
Hourly Std of Log Return: 0.0078
Hourly Sharpe Ratio: 0.2674
Max Drawdown: 0.0331

### Bullish 2

In [ ]:
prices_bullish_2 = pd.read_csv("data/prices/bullish/prices_bullish_2.csv", parse_dates=['timestamp'])
uniform_trade_bullish_2 = simulate_uniform_trade_baseline(prices_bullish_2)
uniform_trade_bullish_2.to_csv("data/baseline_1_uniform_trade/uniform_trade_bullish_2.csv", index=False)

In [108]:
metrics_uniform_trade_bullish_2, final_uniform_trade_bullish_2 = evaluation_metrics_for_baseline(uniform_trade_bullish_2)

=== EVALUATION METRICS ===
Total Return: 0.0889
Hourly Mean Log Return: 0.0005
Hourly Std of Log Return: 0.0059
Hourly Sharpe Ratio: 0.0864
Max Drawdown: 0.0578

### Bullish 3

In [92]:
prices_bullish_3 = pd.read_csv("data/prices/bullish/prices_bullish_3.csv", parse_dates=['timestamp'])
uniform_trade_bullish_3 = simulate_uniform_trade_baseline(prices_bullish_3)
uniform_trade_bullish_3.to_csv("data/baseline_1_uniform_trade/uniform_trade_bullish_3.csv", index=False)

In [109]:
metrics_uniform_trade_bullish_3, final_uniform_trade_bullish_3 = evaluation_metrics_for_baseline(uniform_trade_bullish_3)

=== EVALUATION METRICS ===
Total Return: 0.0229
Hourly Mean Log Return: 0.0001
Hourly Std of Log Return: 0.0056
Hourly Sharpe Ratio: 0.0243
Max Drawdown: 0.0483

### Bearish 1

In [110]:
prices_bearish_1 = pd.read_csv("data/prices/bearish/prices_bearish_1.csv", parse_dates=['timestamp'])

uniform_trade_bearish_1 = simulate_uniform_trade_baseline(prices_bearish_1)
uniform_trade_bearish_1.to_csv("data/baseline_1_uniform_trade/uniform_trade_bearish_1.csv", index=False)

metrics_uniform_trade_bearish_1, final_uniform_trade_bearish_1 = evaluation_metrics_for_baseline(uniform_trade_bearish_1)

=== EVALUATION METRICS ===
Total Return: -0.1081
Hourly Mean Log Return: -0.0007
Hourly Std of Log Return: 0.0104
Hourly Sharpe Ratio: -0.0660
Max Drawdown: 0.1994

### Bearish 2

In [111]:
prices_bearish_2 = pd.read_csv("data/prices/bearish/prices_bearish_2.csv", parse_dates=['timestamp'])

uniform_trade_bearish_2 = simulate_uniform_trade_baseline(prices_bearish_2)
uniform_trade_bearish_2.to_csv("data/baseline_1_uniform_trade/uniform_trade_bearish_2.csv", index=False)

metrics_uniform_trade_bearish_2, final_uniform_trade_bearish_2 = evaluation_metrics_for_baseline(uniform_trade_bearish_2)

=== EVALUATION METRICS ===
Total Return: -0.1397
Hourly Mean Log Return: -0.0009
Hourly Std of Log Return: 0.0068
Hourly Sharpe Ratio: -0.1319
Max Drawdown: 0.1757

### Bearish 3

In [112]:
prices_bearish_3 = pd.read_csv("data/prices/bearish/prices_bearish_3.csv", parse_dates=['timestamp'])

uniform_trade_bearish_3 = simulate_uniform_trade_baseline(prices_bearish_3)
uniform_trade_bearish_3.to_csv("data/baseline_1_uniform_trade/uniform_trade_bearish_3.csv", index=False)

metrics_uniform_trade_bearish_3, final_uniform_trade_bearish_3 = evaluation_metrics_for_baseline(uniform_trade_bearish_3)

=== EVALUATION METRICS ===
Total Return: -0.1785
Hourly Mean Log Return: -0.0012
Hourly Std of Log Return: 0.0092
Hourly Sharpe Ratio: -0.1275
Max Drawdown: 0.1809

### Sideways 1

In [113]:
prices_sideways_1 = pd.read_csv("data/prices/sideways/prices_sideways_1.csv", parse_dates=['timestamp'])

uniform_trade_sideways_1 = simulate_uniform_trade_baseline(prices_sideways_1)
uniform_trade_sideways_1.to_csv("data/baseline_1_uniform_trade/uniform_trade_sideways_1.csv", index=False)

metrics_uniform_trade_sideways_1, final_uniform_trade_sideways_1 = evaluation_metrics_for_baseline(uniform_trade_sideways_1)

=== EVALUATION METRICS ===
Total Return: -0.0544
Hourly Mean Log Return: -0.0003
Hourly Std of Log Return: 0.0058
Hourly Sharpe Ratio: -0.0582
Max Drawdown: 0.0652

### Sideways 2

In [114]:
prices_sideways_2 = pd.read_csv("data/prices/sideways/prices_sideways_2.csv", parse_dates=['timestamp'])

uniform_trade_sideways_2 = simulate_uniform_trade_baseline(prices_sideways_2)
uniform_trade_sideways_2.to_csv("data/baseline_1_uniform_trade/uniform_trade_sideways_2.csv", index=False)

metrics_uniform_trade_sideways_2, final_uniform_trade_sideways_2 = evaluation_metrics_for_baseline(uniform_trade_sideways_2)

=== EVALUATION METRICS ===
Total Return: 0.0254
Hourly Mean Log Return: 0.0002
Hourly Std of Log Return: 0.0039
Hourly Sharpe Ratio: 0.0385
Max Drawdown: 0.0288

### Sideways 3

In [115]:
prices_sideways_3 = pd.read_csv("data/prices/sideways/prices_sideways_3.csv", parse_dates=['timestamp'])

uniform_trade_sideways_3 = simulate_uniform_trade_baseline(prices_sideways_3)
uniform_trade_sideways_3.to_csv("data/baseline_1_uniform_trade/uniform_trade_sideways_3.csv", index=False)

metrics_uniform_trade_sideways_3, final_uniform_trade_sideways_3 = evaluation_metrics_for_baseline(uniform_trade_sideways_3)

=== EVALUATION METRICS ===
Total Return: -0.0359
Hourly Mean Log Return: -0.0002
Hourly Std of Log Return: 0.0054
Hourly Sharpe Ratio: -0.0408
Max Drawdown: 0.0629

## C. Baseline 2: Uniform Buy and Hold

In [ ]:
def simulate_uniform_buy_and_hold_baseline(prices_df):
    
    assets = [col for col in prices_df.columns if col != 'timestamp']

    timestamps = []
    values = []
    all_holdings = []

    row_0 = prices_df.iloc[0]
    capital = 1_000_000 / row_0["usdt_price"] 
    per_asset_allocation = capital / 5
    initial_holdings = per_asset_allocation / row_0[assets].values

    for i in range(len(prices_df)):
        row = prices_df.iloc[i]
        timestamp = row["timestamp"]
        prices = row[assets].values

        total_current_value = np.sum(initial_holdings * prices)

        # Record
        timestamps.append(timestamp)
        values.append(total_current_value)
        all_holdings.append(initial_holdings)

    holdings_df = pd.DataFrame(all_holdings, columns=[a.replace('_price', '_holding') for a in assets])
    results_df = pd.DataFrame({'timestamp': timestamps, 'portfolio_total_value': values})
    merged_df = pd.concat([results_df, holdings_df], axis=1)
    final_df = pd.merge(merged_df, prices_df, on='timestamp')

    return final_df

In [39]:
uniform_hold_bullish_1 = simulate_uniform_buy_and_hold_baseline(prices_bullish_1)
uniform_hold_bullish_1

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2024-11-05 00:00:00,1.000615e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,68006.8008,2400.2317,158.5760,0.164755,0.999386
1,2024-11-05 01:00:00,9.982446e+05,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,67969.5688,2409.7639,158.2116,0.162622,0.999366
2,2024-11-05 02:00:00,9.965965e+05,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,67857.8633,2403.9608,158.2175,0.161914,0.999453
3,2024-11-05 03:00:00,1.001404e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,68216.7021,2419.2786,159.6270,0.162487,0.999443
4,2024-11-05 04:00:00,1.002505e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,68308.7174,2427.8065,159.9727,0.162226,0.999453
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-11-11 19:00:00,1.391549e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,86248.7761,3306.3689,218.1010,0.317950,1.001894
164,2024-11-11 20:00:00,1.403328e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,87004.3072,3356.0327,218.9628,0.321558,1.001616
165,2024-11-11 21:00:00,1.415044e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,87986.4262,3327.2078,219.0813,0.330756,1.001156
166,2024-11-11 22:00:00,1.414714e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,88053.3825,3344.7801,220.4168,0.327745,1.001057
167,2024-11-11 23:00:00,1.450580e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,88728.9508,3375.1192,222.2957,0.351589,1.001128

### Bullish 1

In [117]:
uniform_hold_bullish_1 = simulate_uniform_buy_and_hold_baseline(prices_bullish_1)
uniform_hold_bullish_1.to_csv("data/baseline_2_uniform_hold/uniform_hold_bullish_1.csv", index=False)
uniform_hold_bullish_1

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2024-11-05 00:00:00,1.000615e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,68006.8008,2400.2317,158.5760,0.164755,0.999386
1,2024-11-05 01:00:00,9.982446e+05,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,67969.5688,2409.7639,158.2116,0.162622,0.999366
2,2024-11-05 02:00:00,9.965965e+05,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,67857.8633,2403.9608,158.2175,0.161914,0.999453
3,2024-11-05 03:00:00,1.001404e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,68216.7021,2419.2786,159.6270,0.162487,0.999443
4,2024-11-05 04:00:00,1.002505e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,68308.7174,2427.8065,159.9727,0.162226,0.999453
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-11-11 19:00:00,1.391549e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,86248.7761,3306.3689,218.1010,0.317950,1.001894
164,2024-11-11 20:00:00,1.403328e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,87004.3072,3356.0327,218.9628,0.321558,1.001616
165,2024-11-11 21:00:00,1.415044e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,87986.4262,3327.2078,219.0813,0.330756,1.001156
166,2024-11-11 22:00:00,1.414714e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,88053.3825,3344.7801,220.4168,0.327745,1.001057
167,2024-11-11 23:00:00,1.450580e+06,2.94269,83.37651,1262.000196,1.214667e+06,200245.961672,88728.9508,3375.1192,222.2957,0.351589,1.001128

In [118]:
metrics_uniform_hold_bullish_1, final_uniform_hold_bullish_1 = evaluation_metrics_for_baseline(uniform_hold_bullish_1)

=== EVALUATION METRICS ===
Total Return: 0.4497
Hourly Mean Log Return: 0.0022
Hourly Std of Log Return: 0.0084
Hourly Sharpe Ratio: 0.2654
Max Drawdown: 0.0368

### Bullish 2

In [119]:
uniform_hold_bullish_2 = simulate_uniform_buy_and_hold_baseline(prices_bullish_2)
uniform_hold_bullish_2.to_csv("data/baseline_2_uniform_hold/uniform_hold_bullish_2.csv", index=False)
metrics_uniform_hold_bullish_2, final_uniform_hold_bullish_2 = evaluation_metrics_for_baseline(uniform_hold_bullish_2)

=== EVALUATION METRICS ===
Total Return: 0.0870
Hourly Mean Log Return: 0.0005
Hourly Std of Log Return: 0.0060
Hourly Sharpe Ratio: 0.0829
Max Drawdown: 0.0607

### Bullish 3

In [120]:
uniform_hold_bullish_3 = simulate_uniform_buy_and_hold_baseline(prices_bullish_3)
uniform_hold_bullish_3.to_csv("data/baseline_2_uniform_hold/uniform_hold_bullish_3.csv", index=False)
metrics_uniform_hold_bullish_3, final_uniform_hold_bullish_3 = evaluation_metrics_for_baseline(uniform_hold_bullish_3)

=== EVALUATION METRICS ===
Total Return: 0.0217
Hourly Mean Log Return: 0.0001
Hourly Std of Log Return: 0.0056
Hourly Sharpe Ratio: 0.0229
Max Drawdown: 0.0491

### Bearish 1

In [121]:
uniform_hold_bearish_1 = simulate_uniform_buy_and_hold_baseline(prices_bearish_1)
uniform_hold_bearish_1.to_csv("data/baseline_2_uniform_hold/uniform_hold_bearish_1.csv", index=False)
metrics_uniform_hold_bearish_1, final_uniform_hold_bearish_1 = evaluation_metrics_for_baseline(uniform_hold_bearish_1)

=== EVALUATION METRICS ===
Total Return: -0.1095
Hourly Mean Log Return: -0.0007
Hourly Std of Log Return: 0.0100
Hourly Sharpe Ratio: -0.0698
Max Drawdown: 0.1953

### Bearish 2

In [123]:
uniform_hold_bearish_2 = simulate_uniform_buy_and_hold_baseline(prices_bearish_2)
uniform_hold_bearish_2.to_csv("data/baseline_2_uniform_hold/uniform_hold_bearish_2.csv", index=False)
metrics_uniform_hold_bearish_2, final_uniform_hold_bearish_2 = evaluation_metrics_for_baseline(uniform_hold_bearish_2)

=== EVALUATION METRICS ===
Total Return: -0.1386
Hourly Mean Log Return: -0.0009
Hourly Std of Log Return: 0.0066
Hourly Sharpe Ratio: -0.1354
Max Drawdown: 0.1731

### Bearish 3

In [124]:
uniform_hold_bearish_3 = simulate_uniform_buy_and_hold_baseline(prices_bearish_3)
uniform_hold_bearish_3.to_csv("data/baseline_2_uniform_hold/uniform_hold_bearish_3.csv", index=False)
metrics_uniform_hold_bearish_3, final_uniform_hold_bearish_3 = evaluation_metrics_for_baseline(uniform_hold_bearish_3)

=== EVALUATION METRICS ===
Total Return: -0.1747
Hourly Mean Log Return: -0.0011
Hourly Std of Log Return: 0.0090
Hourly Sharpe Ratio: -0.1284
Max Drawdown: 0.1770

### Sideways 1

In [125]:
uniform_hold_sideways_1 = simulate_uniform_buy_and_hold_baseline(prices_sideways_1)
uniform_hold_sideways_1.to_csv("data/baseline_2_uniform_hold/uniform_hold_sideways_1.csv", index=False)
metrics_uniform_hold_sideways_1, final_uniform_hold_sideways_1 = evaluation_metrics_for_baseline(uniform_hold_sideways_1)

=== EVALUATION METRICS ===
Total Return: -0.0548
Hourly Mean Log Return: -0.0003
Hourly Std of Log Return: 0.0057
Hourly Sharpe Ratio: -0.0592
Max Drawdown: 0.0654

### Sideways 2

In [126]:
uniform_hold_sideways_2 = simulate_uniform_buy_and_hold_baseline(prices_sideways_2)
uniform_hold_sideways_2.to_csv("data/baseline_2_uniform_hold/uniform_hold_sideways_2.csv", index=False)
metrics_uniform_hold_sideways_2, final_uniform_hold_sideways_2 = evaluation_metrics_for_baseline(uniform_hold_sideways_2)

=== EVALUATION METRICS ===
Total Return: 0.0250
Hourly Mean Log Return: 0.0001
Hourly Std of Log Return: 0.0039
Hourly Sharpe Ratio: 0.0378
Max Drawdown: 0.0291

### Sideways 3

In [127]:
uniform_hold_sideways_3 = simulate_uniform_buy_and_hold_baseline(prices_sideways_3)
uniform_hold_sideways_3.to_csv("data/baseline_2_uniform_hold/uniform_hold_sideways_3.csv", index=False)
metrics_uniform_hold_sideways_3, final_uniform_hold_sideways_3 = evaluation_metrics_for_baseline(uniform_hold_sideways_3)

=== EVALUATION METRICS ===
Total Return: -0.0357
Hourly Mean Log Return: -0.0002
Hourly Std of Log Return: 0.0053
Hourly Sharpe Ratio: -0.0408
Max Drawdown: 0.0627

## D. Baseline 3: Momentum

In [157]:
def simulate_momentum_baseline(prices_df, lookback=3, top_k=2):
    assets = [col for col in prices_df.columns if col != 'timestamp']
    
    timestamps = []
    values = []
    all_holdings =[]

    row_0 = prices_df.iloc[0]
    capital = 1_000_000 / row_0["usdt_price"]

    for i in range(len(prices_df)):
        row_now = prices_df.iloc[i]
        timestamp = row_now["timestamp"]
        prices_now = row_now[assets].values

        if i < lookback:
            holdings = np.array([0, 0, 0, 0, 1_000_000])
            total_current_value = capital
        else:
            total_current_value = np.sum(holdings * prices_now)
            # Calculate return over look back period
            row_past = prices_df.iloc[i - lookback + 1]
            prices_past = row_past[assets].values
            momentum = (prices_now - prices_past) / prices_past
            
            # Get top K assets based on momentum
            top_k_indices = np.argsort(momentum)[-top_k:]
            holdings = np.zeros(5)
            allocation_per_asset = capital / top_k
            for j in top_k_indices:
                holdings[j] = allocation_per_asset / prices_now[j]
        
        # Record
        timestamps.append(timestamp)
        values.append(total_current_value)
        all_holdings.append(holdings)

    holdings_df = pd.DataFrame(all_holdings, columns=[a.replace('_price', '_holding') for a in assets])
    results_df = pd.DataFrame({'timestamp': timestamps, 'portfolio_total_value': values})
    merged_df = pd.concat([results_df, holdings_df], axis=1)
    final_df = pd.merge(merged_df, prices_df, on='timestamp')

    return final_df

### Bullish 1

In [158]:
momentum_bullish_1 = simulate_momentum_baseline(prices_bullish_1)
momentum_bullish_1.to_csv("data/baseline_3_momentum/momentum_bullish_1.csv", index=False)
metrics_momentum_bullish_1, final_momentum_bullish_1 = evaluation_metrics_for_baseline(momentum_bullish_1)

=== EVALUATION METRICS ===
Total Return: 0.0402
Hourly Mean Log Return: 0.0002
Hourly Std of Log Return: 0.0159
Hourly Sharpe Ratio: 0.0149
Max Drawdown: 0.1000

### Bullish 2

In [159]:
momentum_bullish_2 = simulate_momentum_baseline(prices_bullish_2)
momentum_bullish_2.to_csv("data/baseline_3_momentum/momentum_bullish_2.csv", index=False)
metrics_momentum_bullish_2, final_momentum_bullish_2 = evaluation_metrics_for_baseline(momentum_bullish_2)

=== EVALUATION METRICS ===
Total Return: -0.0019
Hourly Mean Log Return: -0.0000
Hourly Std of Log Return: 0.0103
Hourly Sharpe Ratio: -0.0011
Max Drawdown: 0.0540

### Bullish 3

In [160]:
momentum_bullish_3 = simulate_momentum_baseline(prices_bullish_3)
momentum_bullish_3.to_csv("data/baseline_3_momentum/momentum_bullish_3.csv", index=False)
metrics_momentum_bullish_3, final_momentum_bullish_3 = evaluation_metrics_for_baseline(momentum_bullish_3)

=== EVALUATION METRICS ===
Total Return: 0.0029
Hourly Mean Log Return: 0.0000
Hourly Std of Log Return: 0.0099
Hourly Sharpe Ratio: 0.0018
Max Drawdown: 0.0494

### Bearish 1

In [161]:
momentum_bearish_1 = simulate_momentum_baseline(prices_bearish_1)
momentum_bearish_1.to_csv("data/baseline_3_momentum/momentum_bearish_1.csv", index=False)
metrics_momentum_bearish_1, final_momentum_bearish_1 = evaluation_metrics_for_baseline(momentum_bearish_1)

=== EVALUATION METRICS ===
Total Return: 0.0051
Hourly Mean Log Return: 0.0000
Hourly Std of Log Return: 0.0137
Hourly Sharpe Ratio: 0.0022
Max Drawdown: 0.0622

### Bearish 2

In [162]:
momentum_bearish_2 = simulate_momentum_baseline(prices_bearish_2)
momentum_bearish_2.to_csv("data/baseline_3_momentum/momentum_bearish_2.csv", index=False)
metrics_momentum_bearish_2, final_momentum_bearish_2 = evaluation_metrics_for_baseline(momentum_bearish_2)

=== EVALUATION METRICS ===
Total Return: 0.0040
Hourly Mean Log Return: 0.0000
Hourly Std of Log Return: 0.0094
Hourly Sharpe Ratio: 0.0026
Max Drawdown: 0.0495

### Bearish 3

In [163]:
momentum_bearish_3 = simulate_momentum_baseline(prices_bearish_3)
momentum_bearish_3.to_csv("data/baseline_3_momentum/momentum_bearish_3.csv", index=False)
metrics_momentum_bearish_3, final_momentum_bearish_3 = evaluation_metrics_for_baseline(momentum_bearish_3)

=== EVALUATION METRICS ===
Total Return: -0.0013
Hourly Mean Log Return: -0.0000
Hourly Std of Log Return: 0.0142
Hourly Sharpe Ratio: -0.0006
Max Drawdown: 0.0667

### Sideways 1

In [164]:
momentum_sideways_1 = simulate_momentum_baseline(prices_sideways_1)
momentum_sideways_1.to_csv("data/baseline_3_momentum/momentum_sideways_1.csv", index=False)
metrics_momentum_sideways_1, final_momentum_sideways_1 = evaluation_metrics_for_baseline(momentum_sideways_1)

=== EVALUATION METRICS ===
Total Return: -0.0047
Hourly Mean Log Return: -0.0000
Hourly Std of Log Return: 0.0073
Hourly Sharpe Ratio: -0.0039
Max Drawdown: 0.0412

### Sideways 2

In [165]:
momentum_sideways_2 = simulate_momentum_baseline(prices_sideways_2)
momentum_sideways_2.to_csv("data/baseline_3_momentum/momentum_sideways_2.csv", index=False)
metrics_momentum_sideways_2, final_momentum_sideways_2 = evaluation_metrics_for_baseline(momentum_sideways_2)

=== EVALUATION METRICS ===
Total Return: -0.0008
Hourly Mean Log Return: -0.0000
Hourly Std of Log Return: 0.0059
Hourly Sharpe Ratio: -0.0008
Max Drawdown: 0.0371

### Sideways 3

In [167]:
momentum_sideways_3 = simulate_momentum_baseline(prices_sideways_3)
momentum_sideways_3.to_csv("data/baseline_3_momentum/momentum_sideways_3.csv", index=False)
metrics_momentum_sideways_3, final_momentum_sideways_3 = evaluation_metrics_for_baseline(momentum_sideways_3)

=== EVALUATION METRICS ===
Total Return: -0.0058
Hourly Mean Log Return: -0.0000
Hourly Std of Log Return: 0.0075
Hourly Sharpe Ratio: -0.0046
Max Drawdown: 0.0483

## E. Baseline 4: Random Baseline

In [ ]:
# Each hour, randomly selects `random_k` assets and invests equally among them.
def simulate_random_baseline(prices_df, random_k=2):
    assets = [col for col in prices_df.columns if col != "timestamp"]

    timestamps = []
    values = []
    all_holdings = []
    
    row_0 = prices_df.iloc[0]
    capital = 1_000_000 / row_0["usdt_price"]

    for i in range(len(prices_df)):
        row = prices_df.iloc[i]
        timestamp = row["timestamp"]
        prices = row[assets].values

        if i == 0:
            holdings = np.array([0, 0, 0, 0, 1_000_000])
            total_current_value = capital
        else:
            total_current_value = np.sum(holdings * prices)

            # Randomly select random_k assets to invest in
            indicies = list(range(5))
            random_selected = random.sample(indicies, random_k)

            # Rebalance portfolio: equally invest in selected assets
            holdings = np.zeros(5)
            allocation_per_asset = total_current_value / random_k
            for j in random_selected:
                holdings[j] = allocation_per_asset / prices[j]
        
        # Record
        timestamps.append(timestamp)
        values.append(total_current_value)
        all_holdings.append(holdings)

    holdings_df = pd.DataFrame(all_holdings, columns=[a.replace('_price', '_holding') for a in assets])
    results_df = pd.DataFrame({'timestamp': timestamps, 'portfolio_total_value': values})
    merged_df = pd.concat([results_df, holdings_df], axis=1)
    final_df = pd.merge(merged_df, prices_df, on='timestamp')

    return final_df

In [51]:
random_bullish_1 = simulate_random_baseline(prices_bullish_1)
random_bullish_1

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2024-11-05 00:00:00,1.000615e+06,0.0,0.000000,0.000000,0.000000e+00,1000000.000000,68006.8008,2400.2317,158.5760,0.164755,0.999386
1,2024-11-05 01:00:00,9.993658e+05,0.0,0.000000,3158.320184,3.072666e+06,0.000000,67969.5688,2409.7639,158.2116,0.162622,0.999366
2,2024-11-05 02:00:00,9.972076e+05,0.0,0.000000,0.000000,3.079445e+06,498876.495904,67857.8633,2403.9608,158.2175,0.161914,0.999453
3,2024-11-05 03:00:00,9.989700e+05,0.0,206.460312,3129.075996,0.000000e+00,0.000000,68216.7021,2419.2786,159.6270,0.162487,0.999443
4,2024-11-05 04:00:00,1.001812e+06,0.0,0.000000,3131.198081,3.087714e+06,0.000000,68308.7174,2427.8065,159.9727,0.162226,0.999453
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-11-11 19:00:00,1.291712e+06,0.0,195.336997,0.000000,0.000000e+00,644635.496782,86248.7761,3306.3689,218.1010,0.317950,1.001894
164,2024-11-11 20:00:00,1.301234e+06,0.0,193.864972,0.000000,0.000000e+00,649567.691513,87004.3072,3356.0327,218.9628,0.321558,1.001616
165,2024-11-11 21:00:00,1.295347e+06,0.0,0.000000,0.000000,1.958163e+06,646926.072770,87986.4262,3327.2078,219.0813,0.330756,1.001156
166,2024-11-11 22:00:00,1.289387e+06,0.0,192.746216,0.000000,0.000000e+00,644012.794496,88053.3825,3344.7801,220.4168,0.327745,1.001057
167,2024-11-11 23:00:00,1.295280e+06,0.0,191.886614,0.000000,1.842036e+06,0.000000,88728.9508,3375.1192,222.2957,0.351589,1.001128

In [60]:
random_bullish_1.to_csv("data/baseline_4_random/temp.csv", index=False)

### Bullish 1

In [ ]:
random_bullish_1 = simulate_random_baseline(prices_bullish_1)
random_bullish_1.to_csv("data/baseline_4_random/random_bullish_1.csv", index=False)
metrics_random_bullish_1, final_random_bullish_1 = evaluation_metrics_for_baseline(random_bullish_1)

=== EVALUATION METRICS ===
Total Return: 0.2233
Hourly Mean Log Return: 0.0012
Hourly Std of Log Return: 0.0088
Hourly Sharpe Ratio: 0.1374
Max Drawdown: 0.0683

### Bullish 2

In [140]:
random_bullish_2 = simulate_random_baseline(prices_bullish_2)
random_bullish_2

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2024-11-18 00:00:00,9.998199e+05,0.000000,0.000000,0.000000,0.0,1000000.000000,89964.6550,3098.8883,235.2862,0.362572,1.000180
1,2024-11-18 01:00:00,1.000114e+06,0.000000,0.000000,2103.824860,0.0,500000.000000,90761.5745,3115.4375,237.6895,0.369684,1.000114
2,2024-11-18 02:00:00,1.004388e+06,0.000000,161.420816,0.000000,0.0,502153.631990,90507.6656,3111.0859,239.7290,0.372299,1.000080
3,2024-11-18 03:00:00,1.004426e+06,0.000000,0.000000,2056.848190,0.0,502208.962049,90669.1319,3111.5463,244.1663,0.372189,1.000008
4,2024-11-18 04:00:00,1.001198e+06,5.533603,0.000000,2063.630683,0.0,0.000000,90465.2619,3101.2543,242.5816,0.372905,1.000070
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-11-24 19:00:00,9.899636e+05,5.137153,0.000000,0.000000,0.0,494770.072027,96353.3222,3328.1993,248.6885,0.418103,1.000428
164,2024-11-24 20:00:00,9.925833e+05,5.123617,0.000000,1978.222267,0.0,0.000000,96863.5395,3342.9295,250.8776,0.427531,1.000425
165,2024-11-24 21:00:00,9.939168e+05,5.121600,148.472896,0.000000,0.0,0.000000,97031.8654,3347.1320,251.1157,0.425843,1.000473
166,2024-11-24 22:00:00,1.001305e+06,5.105644,0.000000,1974.991607,0.0,0.000000,98058.6001,3361.4731,253.4959,0.429371,1.000845
167,2024-11-24 23:00:00,9.994440e+05,5.100907,0.000000,0.000000,0.0,499296.609084,97967.2951,3363.3045,252.7899,0.429903,1.000852

In [141]:
random_bullish_2.to_csv("data/baseline_4_random/random_bullish_2.csv", index=False)
metrics_random_bullish_2, final_random_bullish_2 = evaluation_metrics_for_baseline(random_bullish_2)

=== EVALUATION METRICS ===
Total Return: -0.0004
Hourly Mean Log Return: -0.0000
Hourly Std of Log Return: 0.0070
Hourly Sharpe Ratio: -0.0003
Max Drawdown: 0.0732

### Bullish 3

In [142]:
random_bullish_3 = simulate_random_baseline(prices_bullish_3)
random_bullish_3

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2024-11-26 00:00:00,1.000057e+06,0.000000,0.000000,0.000000,0.000000e+00,1000000.000000,93824.0263,3426.0400,235.3875,0.398912,0.999943
1,2024-11-26 01:00:00,1.000335e+06,5.271548,0.000000,0.000000,1.228701e+06,0.000000,94880.5905,3448.9250,237.5519,0.407070,1.000335
2,2024-11-26 02:00:00,9.985151e+05,0.000000,144.903786,0.000000,1.227389e+06,0.000000,94606.7521,3445.4416,238.7323,0.406764,1.000259
3,2024-11-26 03:00:00,9.955823e+05,0.000000,144.897251,2095.479271,0.000000e+00,0.000000,94501.5469,3435.4769,237.5548,0.405551,1.000388
4,2024-11-26 04:00:00,9.926909e+05,0.000000,145.089722,0.000000,0.000000e+00,496206.427111,94322.7893,3420.9553,237.1791,0.404918,1.000280
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-12-02 19:00:00,1.018268e+06,5.313179,140.948211,0.000000,0.000000e+00,0.000000,95824.7216,3612.2056,223.8774,0.424218,1.000111
164,2024-12-02 20:00:00,1.018239e+06,5.320496,0.000000,0.000000,0.000000e+00,508925.136536,95690.2023,3617.0690,222.9639,0.422470,1.000382
165,2024-12-02 21:00:00,1.016779e+06,0.000000,0.000000,0.000000,1.207217e+06,508271.988431,95430.2323,3616.6530,222.2495,0.421125,1.000231
166,2024-12-02 22:00:00,1.017742e+06,0.000000,0.000000,2267.039804,1.206370e+06,0.000000,95410.9242,3616.6072,224.4649,0.421820,1.000475
167,2024-12-02 23:00:00,1.023672e+06,0.000000,140.447367,0.000000,1.206378e+06,0.000000,95862.9440,3644.3248,225.7742,0.424275,1.000426

In [143]:
random_bullish_3.to_csv("data/baseline_4_random/random_bullish_3.csv", index=False)
metrics_random_bullish_3, final_random_bullish_3 = evaluation_metrics_for_baseline(random_bullish_3)

=== EVALUATION METRICS ===
Total Return: 0.0236
Hourly Mean Log Return: 0.0001
Hourly Std of Log Return: 0.0063
Hourly Sharpe Ratio: 0.0222
Max Drawdown: 0.0798

### Bearish 1

In [144]:
random_bearish_1 = simulate_random_baseline(prices_bearish_1)
random_bearish_1

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2025-01-30 00:00:00,1.000020e+06,0.000000,0.000000,0.000000,0.000000e+00,1000000.000000,104034.4169,3124.6237,231.3156,0.326939,0.999980
1,2025-01-30 01:00:00,9.999670e+05,0.000000,159.327133,0.000000,1.518770e+06,0.000000,104268.1371,3138.0939,234.4911,0.329203,0.999967
2,2025-01-30 02:00:00,1.005842e+06,0.000000,159.426583,0.000000,1.517823e+06,0.000000,104664.5127,3154.5628,237.5322,0.331344,0.999944
3,2025-01-30 03:00:00,1.015820e+06,0.000000,158.681388,0.000000,1.524985e+06,0.000000,105212.6213,3200.8164,240.2198,0.333059,0.999958
4,2025-01-30 04:00:00,1.017645e+06,0.000000,0.000000,2112.076121,0.000000e+00,508832.015327,105488.4609,3197.5740,240.9110,0.334593,0.999981
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2025-02-05 19:00:00,9.334604e+05,4.792205,168.141303,0.000000,0.000000e+00,0.000000,97393.6300,2775.8212,199.5984,0.259367,1.000148
164,2025-02-05 20:00:00,9.310524e+05,4.782783,0.000000,0.000000,0.000000e+00,465492.353380,97333.7608,2763.2065,198.5431,0.257186,1.000073
165,2025-02-05 21:00:00,9.291668e+05,0.000000,0.000000,2335.854135,1.805622e+06,0.000000,96936.5340,2787.1728,198.8923,0.257298,1.000103
166,2025-02-05 22:00:00,9.171863e+05,0.000000,0.000000,2339.339651,0.000000e+00,458550.314180,96489.6033,2760.1648,196.0353,0.254359,1.000093
167,2025-02-05 23:00:00,9.172659e+05,4.746512,0.000000,0.000000,0.000000e+00,458612.500619,96625.2613,2788.2440,196.0789,0.256152,1.000045

In [145]:
random_bearish_1.to_csv("data/baseline_4_random/random_bearish_1.csv", index=False)
metrics_random_bearish_1, final_random_bearish_1 = evaluation_metrics_for_baseline(random_bearish_1)

=== EVALUATION METRICS ===
Total Return: -0.0828
Hourly Mean Log Return: -0.0005
Hourly Std of Log Return: 0.0127
Hourly Sharpe Ratio: -0.0408
Max Drawdown: 0.2044

### Bearish 2

In [146]:
random_bearish_2 = simulate_random_baseline(prices_bearish_2)
random_bearish_2

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2025-02-21 00:00:00,9.997967e+05,0.000000,0.000000,0.000000,0.000000e+00,1000000.000000,98284.4827,2737.3206,174.6249,0.254370,1.000203
1,2025-02-21 01:00:00,1.000188e+06,0.000000,0.000000,0.000000,1.968441e+06,500000.000000,98359.7411,2743.0331,174.4855,0.254056,1.000188
2,2025-02-21 02:00:00,9.980956e+05,0.000000,0.000000,0.000000,1.972714e+06,498919.458296,98169.9476,2738.5563,173.5499,0.252975,1.000257
3,2025-02-21 03:00:00,9.975646e+05,5.079578,181.674310,0.000000,0.000000e+00,0.000000,98193.6412,2745.4751,173.4785,0.252717,1.000214
4,2025-02-21 04:00:00,9.991474e+05,0.000000,181.495619,0.000000,1.966659e+06,0.000000,98252.6086,2752.5385,174.2062,0.254021,1.000195
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2025-02-27 19:00:00,8.809897e+05,0.000000,192.234447,0.000000,0.000000e+00,440685.912330,84078.3636,2291.4460,136.2536,0.205129,0.999566
164,2025-02-27 20:00:00,8.740919e+05,0.000000,0.000000,3199.123082,2.153021e+06,0.000000,83497.8537,2255.5817,136.6143,0.202992,0.999559
165,2025-02-27 21:00:00,8.834490e+05,0.000000,193.646512,3215.804280,0.000000e+00,0.000000,84367.8004,2281.0867,137.3605,0.206229,0.999612
166,2025-02-27 22:00:00,8.878750e+05,5.240981,0.000000,3214.946479,0.000000e+00,0.000000,84705.0385,2291.9031,138.0855,0.206745,0.999788
167,2025-02-27 23:00:00,8.867487e+05,0.000000,192.161390,0.000000,0.000000e+00,443395.404815,84718.8275,2307.3020,137.7127,0.207021,0.999953

In [147]:
random_bearish_2.to_csv("data/baseline_4_random/random_bearish_2.csv", index=False)
metrics_random_bearish_2, final_random_bearish_2 = evaluation_metrics_for_baseline(random_bearish_2)

=== EVALUATION METRICS ===
Total Return: -0.1131
Hourly Mean Log Return: -0.0007
Hourly Std of Log Return: 0.0072
Hourly Sharpe Ratio: -0.0992
Max Drawdown: 0.1634

### Bearish 3

In [148]:
random_bearish_3 = simulate_random_baseline(prices_bearish_3)
random_bearish_3

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2025-03-03 00:00:00,9.997874e+05,0.000000,0.000000,0.000000,0.000000e+00,1000000.000000,93384.2036,2467.1532,174.5393,0.235389,1.000213
1,2025-03-03 01:00:00,1.000096e+06,5.369297,0.000000,0.000000,0.000000e+00,500000.000000,93130.9855,2460.2504,172.6851,0.231429,1.000096
2,2025-03-03 02:00:00,1.001288e+06,0.000000,0.000000,0.000000,2.177257e+06,500642.450425,93361.6898,2448.5505,171.6575,0.229943,1.000003
3,2025-03-03 03:00:00,9.971727e+05,5.374825,0.000000,0.000000,0.000000e+00,498585.871210,92763.2767,2442.0783,170.1082,0.228053,1.000001
4,2025-03-03 04:00:00,9.979691e+05,0.000000,0.000000,2940.789127,2.177086e+06,0.000000,92911.7917,2451.3575,169.6771,0.229198,0.999997
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2025-03-09 19:00:00,8.877812e+05,5.369345,0.000000,0.000000,2.586535e+06,0.000000,82671.2826,2041.4972,129.2483,0.171616,1.000643
164,2025-03-09 20:00:00,8.901276e+05,0.000000,0.000000,0.000000,2.594312e+06,444728.277747,83138.2554,2048.7784,128.4520,0.171554,1.000754
165,2025-03-09 21:00:00,8.842797e+05,0.000000,218.201877,3451.338001,0.000000e+00,0.000000,81939.4262,2026.2881,128.1068,0.169298,1.000761
166,2025-03-09 22:00:00,8.772603e+05,5.456019,0.000000,3453.073730,0.000000e+00,0.000000,80393.8015,2011.2138,127.0260,0.167321,1.000490
167,2025-03-09 23:00:00,8.782845e+05,0.000000,217.267611,3466.328879,0.000000e+00,0.000000,80795.4492,2021.2045,126.6880,0.168523,1.000484

In [149]:
random_bearish_3.to_csv("data/baseline_4_random/random_bearish_3.csv", index=False)
metrics_random_bearish_3, final_random_bearish_3 = evaluation_metrics_for_baseline(random_bearish_3)

=== EVALUATION METRICS ===
Total Return: -0.1215
Hourly Mean Log Return: -0.0008
Hourly Std of Log Return: 0.0083
Hourly Sharpe Ratio: -0.0932
Max Drawdown: 0.1239

### Sideways 1

In [150]:
random_sideways_1 = simulate_random_baseline(prices_sideways_1)
random_sideways_1

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2024-08-09 00:00:00,9.996321e+05,0.000000,0.000000,0.000000,0.000000e+00,1000000.000000,61257.4370,2667.4673,161.4598,0.107046,1.000368
1,2024-08-09 01:00:00,1.000330e+06,8.140303,0.000000,0.000000,0.000000e+00,500000.000000,61443.0406,2672.4434,160.5484,0.106111,1.000330
2,2024-08-09 02:00:00,9.990297e+05,0.000000,0.000000,0.000000,4.726788e+06,499398.636855,61289.2862,2671.5673,158.6511,0.105677,1.000233
3,2024-08-09 03:00:00,1.001696e+06,0.000000,185.727420,3144.549875,0.000000e+00,0.000000,61404.4036,2696.6841,159.2750,0.106241,1.000234
4,2024-08-09 04:00:00,9.860508e+05,8.113712,185.216061,0.000000,0.000000e+00,0.000000,60764.4714,2661.8933,156.3544,0.104452,1.000219
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-08-15 19:00:00,9.273855e+05,0.000000,0.000000,3305.904231,0.000000e+00,463562.041182,57091.1576,2551.4218,140.2620,0.099288,1.000282
164,2024-08-15 20:00:00,9.283906e+05,0.000000,182.261359,0.000000,0.000000e+00,464008.778740,56650.4838,2546.8661,140.5492,0.099146,1.000402
165,2024-08-15 21:00:00,9.332447e+05,0.000000,0.000000,3284.818965,4.693309e+06,0.000000,57658.0232,2573.6433,142.0542,0.099423,1.000345
166,2024-08-15 22:00:00,9.434423e+05,8.180646,0.000000,0.000000,4.705536e+06,0.000000,57663.0721,2578.3625,143.9796,0.100248,1.000339
167,2024-08-15 23:00:00,9.432355e+05,0.000000,0.000000,3301.951606,0.000000e+00,471478.846230,57581.1147,2571.3678,142.8300,0.100347,1.000295

In [151]:
random_sideways_1.to_csv("data/baseline_4_random/random_sideways_1.csv", index=False)
metrics_random_sideways_1, final_random_sideways_1 = evaluation_metrics_for_baseline(random_sideways_1)

=== EVALUATION METRICS ===
Total Return: -0.0564
Hourly Mean Log Return: -0.0003
Hourly Std of Log Return: 0.0067
Hourly Sharpe Ratio: -0.0520
Max Drawdown: 0.0834

### Sideways 2

In [153]:
random_sideways_2 = simulate_random_baseline(prices_sideways_2)
random_sideways_2

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2024-08-16 00:00:00,9.997873e+05,0.000000,0.000000,0.000000,0.000000e+00,1000000.000000,57511.0192,2574.4121,142.1852,0.100528,1.000213
1,2024-08-16 01:00:00,1.000180e+06,8.686233,0.000000,0.000000,4.986991e+06,0.000000,57572.6957,2574.0516,142.2313,0.100279,1.000180
2,2024-08-16 02:00:00,1.010180e+06,8.673787,0.000000,3522.039952,0.000000e+00,0.000000,58231.7486,2595.5974,143.4083,0.101136,1.000219
3,2024-08-16 03:00:00,1.003412e+06,8.661184,0.000000,0.000000,0.000000e+00,501606.321087,57925.8048,2581.5499,142.2403,0.100729,1.000199
4,2024-08-16 04:00:00,1.007005e+06,0.000000,193.763454,0.000000,4.958265e+06,0.000000,58340.1159,2598.5421,142.7448,0.101548,1.000208
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-08-22 19:00:00,9.833235e+05,0.000000,0.000000,0.000000,4.688610e+06,491536.859804,60313.5790,2607.4105,142.8288,0.104863,1.000254
164,2024-08-22 20:00:00,9.855691e+05,8.119396,187.694558,0.000000,0.000000e+00,0.000000,60692.2651,2625.4600,143.4718,0.105351,1.000171
165,2024-08-22 21:00:00,9.844220e+05,0.000000,187.532586,0.000000,4.669722e+06,0.000000,60569.2689,2624.6693,143.4358,0.105405,1.000180
166,2024-08-22 22:00:00,9.848795e+05,0.000000,187.594992,0.000000,0.000000e+00,492352.953778,60456.6558,2625.0155,143.2996,0.105489,1.000176
167,2024-08-22 23:00:00,9.846722e+05,8.151460,187.643158,0.000000,0.000000e+00,0.000000,60398.5204,2623.7893,143.3316,0.105323,1.000222

In [154]:
random_sideways_2.to_csv("data/baseline_4_random/random_sideways_2.csv", index=False)
metrics_random_sideways_2, final_random_sideways_2 = evaluation_metrics_for_baseline(random_sideways_2)

=== EVALUATION METRICS ===
Total Return: -0.0151
Hourly Mean Log Return: -0.0001
Hourly Std of Log Return: 0.0046
Hourly Sharpe Ratio: -0.0200
Max Drawdown: 0.0390

### Sideways 3

In [155]:
random_sideways_3 = simulate_random_baseline(prices_sideways_3)
random_sideways_3

,timestamp,portfolio_total_value,btc_holding,eth_holding,sol_holding,doge_holding,usdt_holding,btc_price,eth_price,sol_price,doge_price,usdt_price
0,2024-08-28 00:00:00,9.997273e+05,0.000000,0.000000,0.000000,0.000000e+00,1000000.000000,59125.7260,2442.3780,146.1594,0.098626,1.000273
1,2024-08-28 01:00:00,1.000176e+06,0.000000,0.000000,0.000000,5.042229e+06,500000.000000,59409.9149,2444.8139,147.1026,0.099180,1.000176
2,2024-08-28 02:00:00,9.992494e+05,0.000000,202.955660,0.000000,5.047859e+06,0.000000,59380.1541,2461.7430,146.9407,0.098978,1.000364
3,2024-08-28 03:00:00,1.007240e+06,8.440141,0.000000,0.000000,5.045789e+06,0.000000,59669.6007,2480.4102,148.3523,0.099810,1.000350
4,2024-08-28 04:00:00,1.002071e+06,0.000000,0.000000,3394.974070,5.046183e+06,0.000000,59368.0229,2473.0825,147.5815,0.099290,1.000390
...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-09-03 19:00:00,9.624002e+05,0.000000,196.588844,0.000000,4.924185e+06,0.000000,58047.7479,2447.7487,131.0297,0.097722,1.000005
164,2024-09-03 20:00:00,9.674963e+05,0.000000,0.000000,3702.068281,0.000000e+00,483729.206025,58236.9411,2463.8247,130.6697,0.098115,1.000039
165,2024-09-03 21:00:00,9.659570e+05,0.000000,0.000000,0.000000,4.931619e+06,482897.499199,58143.6887,2465.3012,130.2371,0.097935,1.000168
166,2024-09-03 22:00:00,9.644823e+05,0.000000,196.474796,3720.031992,0.000000e+00,0.000000,57889.9402,2454.4682,129.6336,0.097634,1.000189
167,2024-09-03 23:00:00,9.516168e+05,8.272795,0.000000,3726.537562,0.000000e+00,0.000000,57514.8333,2425.9552,127.6811,0.096829,1.000201

In [156]:
random_sideways_3.to_csv("data/baseline_4_random/random_sideways_3.csv", index=False)
metrics_random_sideways_3, final_random_sideways_3 = evaluation_metrics_for_baseline(random_sideways_3)

=== EVALUATION METRICS ===
Total Return: -0.0481
Hourly Mean Log Return: -0.0003
Hourly Std of Log Return: 0.0058
Hourly Sharpe Ratio: -0.0509
Max Drawdown: 0.0866

## F. Imitate an Average Investor (Everyday Person)

Check Excel file